stages:
  collect_data:
    cmd: python scripts/fetch_data.py
    deps:
      - scripts/fetch_data.py
    outs:
      - data/raw_data.csv

  preprocess_data:
    cmd: python scripts/preprocess.py
    deps:
      - data/raw_data.csv
      - scripts/preprocess.py
    outs:
      - data/processed_data.csv

  train_model:
    cmd: python scripts/train_model.py
    deps:
      - data/processed_data.csv
      - scripts/train_model.py
    outs:
      - models/model.pkl
